const jCategory = [
    {
        index: 0,
        image: "../images/google.png",
        title: "Web devloper",
        rate: "$900 - $1200/m",
        av: "Full Time",
        companyName: "Google",
        location: "New York",
        vacancy: "02",
        hours: "50/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "Work from Home",
        education: "Bachelor degree in any Computer Science Course.",
        experience: "2 to 5 year(s)"

    },
    {
        index: 1,
        image: "../images/uber.png",
        title: "Freelancer",
        rate: "$1000 - $1400/m",
        av: "Freelancer",
        companyName: "Uber",
        location: "Washington DC",
        vacancy: "05",
        hours: "40/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "- Freelancer",
        education: "- Degree in any Computer Science Course.",
        experience: "- 1 to 5 year(s)"
    },
    {
        index: 2,
        image: "../images/linkedin.png",
        title: "Business Associate",
        rate: "$900 - $1200/m",
        av: "Business Associate",
        companyName: "LinkedIn",
        location: "Amsterdam",
        vacancy: "03",
        hours: "60/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "- Work from Home",
        education: "- Bachelor degree in any Computer Science Course.",
        experience: "- 3 to 5 year(s)"
    },
    {
        index: 3,
        image: "../images/facebook.png",
        title: "Digital Marketing",
        rate: "$9000 - $1350/m",
        av: "Digital Marketing",
        companyName: "Facebook",
        location: "Atlanta",
        vacancy: "07",
        hours: "80/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "- Work from Home",
        education: "- Bachelor degree in any Computer Science Course.",
        experience: "- 3 to 5 year(s)"
    },
    {
        index: 4,
        image: "../images/yahoo.png",
        title: "User Experience",
        rate: "$1000 - $1200/m",
        av: "User Experience",
        companyName: "Yahoo",
        location: "Delhi",
        vacancy: "02",
        hours: "85/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "- Work from Home",
        education: "- Bachelor degree in any Computer Science Course.",
        experience: "- 2 to 5 year(s)"
    },
    {
        index: 5,
        image: "../images/apple.png",
        title: "Web Developer",
        rate: "$1000 - $1200/m",
        av: "Web Developer",
        companyName: "Apple",
        location: "apple City",
        vacancy: "02",
        hours: "50/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "- remote",
        education: "- Bachelor degree in any Computer Science Course.",
        experience: "- 3 to 5 year(s)"
    },
    {
        index: 6,
        image: "../images/instagram.png",
        title: "Product Designer",
        rate: "$1000 - $1200/m",
        av: "Product Designer",
        companyName: "Instagram",
        location: "San Francisco",
        vacancy: "05",
        hours: "40/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "- Work from Home",
        education: "- Degree in any Computer Science Course.",
        experience: "- 3 to 5 year(s)"
    },
    {
        index: 7,
        image: "../images/wordpress.png",
        title: "Freelancer",
        rate: "$1000 - $1100/m",
        av: "Freelancer",
        companyName: "WordPress",
        location: "London",
        vacancy: "01",
        hours: "50/ Week",
        description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        workPlace: "- Freelancer",
        education: "- Degree in any Computer Science Course.",
        experience: "- 2 to 3 year(s)"
    },
];
